Repository isekai-rpg/isekai, pull requests merged in 2024-01, with the labels that each got.

#3 fix(core): register shutdown logic with scheduler
  src/main/kotlin/me/santio/isekai/Isekai.kt
Labels: enhancement

#4 fix(player): improve skin loading performance
  src/main/kotlin/me/santio/isekai/helper/OkHttp.kt
  src/main/kotlin/me/santio/isekai/io/mojang/UnifiedMojangAPI.kt
  src/main/kotlin/me/santio/isekai/listeners/PlayerListener.kt
Labels: bug, enhancement

#6 Fixes Logging
  build.gradle.kts
Labels: bug

#8 fix(player): improve skin load performance
  src/main/kotlin/me/santio/isekai/listeners/PlayerListener.kt
Labels: bug

#7 Implement Basic Entity System
  src/main/kotlin/me/santio/isekai/Isekai.kt
  src/main/kotlin/me/santio/isekai/commands/SpawnEntity.kt
  src/main/kotlin/me/santio/isekai/entity/AIGroupHolder.kt
  src/main/kotlin/me/santio/isekai/entity/EntityStats.kt
  src/main/kotlin/me/santio/isekai/entity/IsekaiCreature.kt
  src/main/kotlin/me/santio/isekai/entity/StatsHolder.kt
  src/main/kotlin/me/santio/isekai/entity/types/EliteZombieCreature.kt
  src/main/kotlin/me/santio/isekai/handler/block/DoorHandler.kt
  src/main/kotlin/me/santio/isekai/helper/minestom/StatusHelper.kt
  src/main/kotlin/me/santio/isekai/listeners/EntityDamageListener.kt
  src/main/kotlin/me/santio/isekai/listeners/PlayerListener.kt
Labels: enhancement
